### ISSUE TITLE
Usage example not working

### ISSUE THREAD

**Issue by weirdbricks** [dseres/dag#3]
Hi,

I'm trying the example and getting an error.

The code (copy paste from the "Usage") 

```
require "dag"
dag = Graph(Int32).new 
(1...10).each { |i| dag.add i}

puts dag.inspect
```

Error:

```
crystal src/dag01.cr 
Showing last frame. Use --error-trace for full trace.

In src/dag01.cr:2:7

 2 | dag = Graph(Int32).new 
           ^----
Error: undefined constant Graph
```

If I change it to this it works:

```
require "dag"
dag = Dag::Graph(Int32).new 
(1...10).each { |i| dag.add i}

puts dag.inspect
```

Am I doing something wrong? 

Thanks!

**Comment by weirdbricks** [comment]
Forgot to mention, this is Crystal 1.2.1:

```
crystal -v
Crystal 1.2.1 [4e6c0f26e] (2021-10-21)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

Shards: 

```
shards list
Shards installed:
  * dag (0.9.0)
```

**Comment by dseres** [comment]
Hi,
Thank you for your feedback, I will fix it. 

I am very happy. You are the first who contributed in one of my projects. 

I am still learning crystal, and i like it.  But the tooling need some improvement. Crystal doesn't compile the code examples in comments like the Rust language. 

Thanks!

**Comment by dseres** [comment]
Thanks!

**Comment by weirdbricks** [comment]
Thank you very much for the quick fix :)
