### ISSUE TITLE
'def each(&)' example from the API not working

### ISSUE THREAD

**Issue by weirdbricks** [dseres/dag#5]
Hi again! 

I'm looking at the API Pages here: https://dseres.github.io/dag/Dag/Graph.html#each%28%26%29-instance-method

I'm trying this example (copy paste)

```
require "dag"
dag = Dag::Graph(Int32).new
dag.add(1)
dag.add(2)
dag.add(3)
dag.add(4)
dag.add(1, 3)
dag.add(2, 4)
```

and I get: 

```
crystal src/dag02.cr 
Showing last frame. Use --error-trace for full trace.

In src/dag02.cr:7:5

 7 | dag.add(1, 3)
         ^--
Error: wrong number of arguments for 'Dag::Graph(Int32)#add' (given 2, expected 1)

Overloads are:
 - Dag::Graph(V)#add(vertex : V)
```

1. If I understand correctly, the `dag.add_edge` should be used to indicate the predecessors and successors right? Maybe I'm doing it wrong :sweat_smile: 
2. Note, just like before I had to change the line: 
```
dag = Graph(Int32).new
```
to:

```
dag = Dag::Graph(Int32).new
```
Thanks!

**Comment by dseres** [comment]
Thank for your feedback. I will review all of the comments and fix them.

**Comment by weirdbricks** [comment]
thanks again!
