### ISSUE TITLE
Can you create a drawing out of the graph?

### ISSUE THREAD

**Issue by weirdbricks** [dseres/dag#7]
Hi!

Is there an easy way to create a drawing out of a graph? 

Thanks!

**Comment by dseres** [comment]
Hi, 
yes, a few days ago i added a an example to the project: 
[print_as_dotfile.cr](https://github.com/dseres/dag/blob/master/examples/print_as_dotfile.cr)  
You can convert a dotfile to any format with graphwiz or any other implementation. 

I hope, my answer was useful.

**Comment by weirdbricks** [comment]
Thanks! I'll try this out :)
